### ISSUE TITLE
strange error

### ISSUE THREAD

**Issue by fxpester** [rilleralle/k8s-graph#2]
just tried your project, but got error:
```
[root@s05v01a k8s-graph]# kubectl logs k8s-graph-6889d69644-n6k4l k8s-graph
standard_init_linux.go:178: exec user process caused "exec format error"
[root@s05v01a k8s-graph]# kubectl logs k8s-graph-6889d69644-n6k4l kubectl
standard_init_linux.go:178: exec user process caused "exec format error"
```

**Comment by fxpester** [comment]
my bad, I used arm64 images on x86_64 machine

**Comment by rilleralle** [comment]
Hi @fxpester, if you have any problems with the setup, please let me know.
Not sure if the README covers all corner cases.

**Comment by fxpester** [comment]
README and k8s yaml instruct you how to deploy this project on ARM64 arch

so, if i remove 'arm64' I can get main image start on k8s but looks like it depend on kubectl container and there is no container named rilleralle/kubectl - only rilleralle/kubectl-arm64

**Comment by rilleralle** [comment]
True. There is an x86_64 container of kubectl available from Google. I also used this one for development.
You can try this:
```
      - name: kubectl
        image: gcr.io/google_containers/kubectl:v0.18.0-120-gaeb4ac55ad12b1-dirty
        args:
          - "proxy"
          - "-p"
          - "8001"
```
